version: '3'

services:
  es:
    image: elasticsearch:7.3.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    networks:
      - esnetwork
  kibana:
    image: kibana:7.3.2
    ports:
      - 5601:5601
    networks:
      - esnetwork

networks:
  esnetwork:
